name = "collaboard"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[site]
bucket = "./dist"

[dev]
port = 8787
